create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
set_input_delay -clock [get_clocks clk] -clock_fall -min -add_delay 2.000 [get_ports reset]
set_input_delay -clock [get_clocks clk] -clock_fall -max -add_delay 4.000 [get_ports reset]
set_input_delay -clock [get_clocks clk] -min -add_delay 2.000 [get_ports reset]
set_input_delay -clock [get_clocks clk] -max -add_delay 4.000 [get_ports reset]

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

set_property CONFIG_MODE SPIx1 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property PULLDOWN true [get_ports reset]
set_property PACKAGE_PIN D12 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]

set_property PACKAGE_PIN B16 [get_ports {ram_address[7]}]
set_property PACKAGE_PIN B17 [get_ports {ram_address[6]}]
set_property PACKAGE_PIN A15 [get_ports {ram_address[5]}]
set_property PACKAGE_PIN A16 [get_ports {ram_address[4]}]
set_property PACKAGE_PIN A13 [get_ports {ram_address[3]}]
set_property PACKAGE_PIN A14 [get_ports {ram_address[2]}]
set_property PACKAGE_PIN B18 [get_ports {ram_address[1]}]
set_property PACKAGE_PIN A18 [get_ports {ram_address[0]}]
set_property PACKAGE_PIN G13 [get_ports {ram_data[7]}]
set_property PACKAGE_PIN D14 [get_ports {ram_data[6]}]
set_property PACKAGE_PIN C14 [get_ports {ram_data[5]}]
set_property PACKAGE_PIN B13 [get_ports {ram_data[4]}]
set_property PACKAGE_PIN B14 [get_ports {ram_data[3]}]
set_property PACKAGE_PIN C12 [get_ports {ram_data[2]}]
set_property PACKAGE_PIN B12 [get_ports {ram_data[1]}]
set_property PACKAGE_PIN B11 [get_ports {ram_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_address[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_address[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_address[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_address[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_address[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_address[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_address[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_address[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ram_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ram_read_en]
set_property IOSTANDARD LVCMOS33 [get_ports ram_write_en]
set_property PACKAGE_PIN F13 [get_ports ram_read_en]
set_property PACKAGE_PIN F14 [get_ports ram_write_en]

